export const MEMORY_AWARENESS_INSTRUCTIONS = [
  "\n\n## Memory",
  "Your context contains: the full content of MEMORY.md, IDENTITY.md, USER.md, plus a **Project Memory Index** — the heading map (with word counts) of this project's three memory files. Treat that index as your map of what is already known.",
  "",
  "### The Three Project Memory Files",
  "**A dedicated memory-keeper background agent maintains these files.** You READ them freely; you do NOT write them (writes are blocked).",
  "",
  "**1. `project` → project.md** — stable project knowledge: facts, architecture, features, conventions, decisions (and why), constraints, open questions. Headings: Facts / Decisions / Constraints / Open Questions.",
  "**2. `corrections` → corrections.md** — mistakes, failed fixes, debugging lessons, user corrections. Headings: Corrections.",
  "**3. `environment` → environment.md** — how to work here: build/test/deploy commands, important paths, tooling + versions. Headings: Commands / Paths / Tooling.",
  "",
  "**Never memory-worthy:** file-by-file code structure, implementation details that change frequently, anything trivially discoverable by reading the code.",
  "",
  "### How to Get Something Remembered (the <mem> protocol)",
  "When something is worth persisting to project memory, include it in your reply inside `<mem></mem>` tags:",
  "- Put either a concise memory candidate (ready-to-save text) or a short explanation of what should be remembered",
  "- The memory-keeper reads your conversation after each turn, extracts the key points from tagged content, and writes them to the correct file and heading (it sees the current memory index, so no duplication)",
  "- Tag content is HIGH PRIORITY — never lose it. Everything outside the tags is harvested only when clearly memory-worthy",
  "- Example: `...the fix is deployed. <mem>Record: authentication uses JWT with refresh-token rotation (decision: stateless > server sessions)</mem>`",
  "",
  "### Section Addressing with headingPath (for reads)",
  "- `read` + headingPath → one section including its subsections (e.g. [\"Project Memory\", \"Facts\"])",
  "- `index` action → fresh heading index of ANY target; use it after several turns (the keeper may have written new sections)",
  "- `search` → semantic search over global memory + THIS project's memory (other projects are NOT in scope; pass projectName to search a specific project instead); results carry the heading path — then `read` that section for the full context",
  "",
  "### Workflow",
  "1. **Before answering project questions**: check the index, `read` relevant sections (or `search` first in large projects) — never answer from exploration alone without checking memory",
  "2. **When something memory-worthy happens** (discovery, decision, correction, new command): signal it with `<mem>...</mem>` tags in your reply",
  "3. **When corrected or when you err**: signal it with `<mem>` tags immediately — same-session recording keeps the lesson accurate",
  "4. **When files or sections show 0/0 counts in the index**: empty scaffolding — good targets to fill via `<mem>` signals as you learn",
  "5. **Before making any Architectural or Design Change**: Read the relevant sections of the project project.md",
  "6. **Before making any Environmental Change**: Read the relevant sections of the project environment.md",
  "7. **Before your First Exploration or Planning of the Session**: Read the relevant sections of the project corrections.md so you don't have to make assumptions and repeat mistakes",
  "",
  "### Routing Rules",
  "```",
  "User facts/preferences → USER.md (you write these directly)",
  "Your persona/behavior rules → IDENTITY.md (you write these directly)",
  "Crucial cross-project technical knowledge → MEMORY.md (you write these directly, explicit only)",
  "Everything about THIS project → the memory-keeper via <mem> tags (you do NOT write project files)",
  "```",
  "",
  "### Hard Rules",
  "- NEVER ask permission to update memory — just do it (globals) or signal it (<mem> for project files)",
  "- NEVER write the same information in two files",
  "- NEVER include timestamps in content — the system auto-stamps every entry",
  "- Keep <mem> signals short and to the point — they are extracted, not copied verbatim (unless already concise)",
  "- If your map seems stale (the keeper wrote new content), refresh with the `index` action",
  "",
].join("\n");

/**
 * Legacy multi-writer instructions — used only when the keeper is disabled in
 * keeper-config.json. Main agent writes project files itself in that mode.
 */
export const MEMORY_AWARENESS_INSTRUCTIONS_NO_KEEPER = [
  "\n\n## Memory",
  "Your context contains: the full content of MEMORY.md, IDENTITY.md, USER.md, plus a **Project Memory Index** — the heading map (with word counts) of this project's three memory files. Treat that index as your map of what is already known.",
  "",
  "### The Three Project Memory Files",
  "Every project has three structured files. Know what belongs in each and which heading to write under:",
  "",
  "**1. `project` → project.md** — stable knowledge about the project itself. Structure: Facts / Decisions / Constraints / Open Questions.",
  "- Facts: what the project does, architecture, features, conventions",
  "- Decisions: why an approach was chosen",
  "- Constraints: hard limits (versions, budgets, requirements)",
  "- Open Questions: unresolved items awaiting an answer",
  "- Write one-off entries: `write` with headingPath [\"Project Memory\", \"Facts\"] (or \"Decisions\", etc.). For related groups of entries, create a topical `### ` sub-heading first (see below).",
  "",
  "**2. `corrections` → corrections.md** — mistakes and lessons. Structure: Corrections.",
  "- Record: wrong assumptions, failed fixes that worked/didn't, debugging lessons, user corrections",
  "- Write as: **Initial mistake** / **Correction** / **Lesson** under [\"Corrective Memory\", \"Corrections\"]",
  "- Record the correction in the SAME session it happens",
  "",
  "**3. `environment` → environment.md** — how to work in this project. Structure: Commands / Paths / Tooling.",
  "- Commands: build/test/deploy commands",
  "- Paths: important files, directories, configs",
  "- Tooling: required tools, versions, setup steps",
  "- Write new entries under [\"Environment Memory\", \"Commands\"] (or \"Paths\" / \"Tooling\")",
  "",
  "**Never record in project files:** file-by-file code structure, implementation details that change frequently, or anything trivially discoverable by reading the code.",
  "",
  "### Organize with Sub-headings (structure IS retrieval)",
  "- The search index chunks memory PER HEADING — a flat H2 that accumulates many entries becomes one giant chunk and search results stop targeting specific facts.",
  "- When a heading already holds several entries (the index shows its word counts) and new content forms a distinct topic, create a `### ` sub-heading under it with `createMissing: true` — e.g. headingPath: [\"Project Memory\", \"Facts\", \"Build Commands\"].",
  "- Mirror real knowledge topology (module names, feature areas) — never nest deeper than H4, never duplicate an existing heading.",
  "- Prefer `edit` over re-adding: correct or extend the existing entry instead of appending a near-duplicate.",
  "",
  "### Section Addressing with headingPath",
  "- `read` + headingPath → one section including its subsections (e.g. [\"Project Memory\", \"Facts\"])",
  "- `write` + headingPath → insert directly under that heading, before its subsections; `createMissing: true` creates missing headings",
  "- `edit`/`delete` + headingPath → oldString scoped to that section only, must match exactly once",
  "- `index` action → fresh heading index of ANY target; use it after several writes in a session",
  "- `search` → semantic search over global memory + THIS project's memory (other projects are NOT in scope; pass projectName to search a specific project instead); results carry the heading path — then `read` that section for the full context",
  "",
  "### Workflow",
  "1. **Before answering project questions**: check the index, `read` relevant sections (or `search` first in large projects) — never answer from exploration alone without checking memory",
  "2. **While working**: when you learn something new, `write` it under the right heading in the right file — no permission needed",
  "3. **When corrected or when you err**: record it in corrections.md immediately",
  "4. **When files or sections show 0/0 counts in the index**: they are empty scaffolding — fill them as you learn",
  "5. **Before making any Architectural or Design Change**: Read the relevant sections of the project project.md",
  "6. **Before making any Environmental Change**: Read the relevant sections of the project environment.md",
  "7. **Before your First Exploration or Planning of the Session**: Read the relevant sections of the project corrections.md so you don't have to make assumptions and repeat mistakes",
  "",
  "### Routing Rules",
  "```",
  "User facts/preferences → USER.md",
  "Your persona/behavior rules → IDENTITY.md",
  "Crucial cross-project technical knowledge → MEMORY.md (explicit only)",
  "Everything about THIS project → project folder (project/corrections/environment)",
  "```",
  "",
  "### Hard Rules",
  "- NEVER ask permission to update memory — just do it",
  "- NEVER write the same information in two files",
  "- NEVER include timestamps in content — the system auto-stamps every entry",
  "- Keep entries short and distilled — at most ~2-4 sentences (~400 chars); never paste task specs, requirement lists, or long quotes verbatim. The index exists so future sessions navigate without reading whole files",
  "- If your map seems stale (after writes), refresh with the `index` action",
  "",
].join("\n");

export const BOOTSTRAP_INSTRUCTIONS = [
  "\n\n## Memory Setup",
  "This is your first run. Read BOOTSTRAP.md above and follow the setup instructions.",
  "Ask the user questions interactively, then write to MEMORY.md, IDENTITY.md, and USER.md.",
  "After setup is complete, delete BOOTSTRAP.md using the memory tool or filesystem.",
].join("\n");

/**
 * Context appended to OpenCode's default compaction prompt via the
 * "experimental.session.compacting" hook. `indexSection` is the fresh rendered
 * heading index of the project's three memory files (what is already saved);
 * `projectName` identifies the memory scope.
 */
export function buildCompactionContext(
  projectName: string,
  indexSection: string
): string {
  return [
    "## Memory State (plugin: opencode-auto-mem)",
    `Project: ${projectName} — memory files: project.md, corrections.md, environment.md`,
    "",
    "Current heading index of these files (what is ALREADY saved to persistent memory):",
    indexSection,
    "",
    "## Summarization rules for this session's memory",
    "1. The conversation you are summarizing belongs to a session that has persistent memory (the indexed files above).",
    "2. PRESERVE VERBATIM in your summary any session knowledge NOT already in the files above: project facts, decisions and their reasons, corrections/mistakes and lessons, environment details (commands, paths, tooling) — these may not yet be written to memory.",
    "3. PRESERVE the current task state and next steps.",
    "4. Facts already present in the indexed memory files need only a one-line reference.",
    "5. Your summary will be read by an agent that has the memory context re-injected — write the summary as \"what happened in this session beyond what memory holds\".",
  ].join("\n");
}